# YAML Linting Configuration for BSMarker
extends: default

rules:
  # Line length
  line-length:
    max: 120
    level: warning
    allow-non-breakable-inline-mappings: true

  # Indentation
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Brackets and braces
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0

  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0

  # Colons
  colons:
    max-spaces-before: 0
    max-spaces-after: 1

  # Commas
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1

  # Comments
  comments:
    require-starting-space: true
    min-spaces-from-content: 2

  # Document start/end
  document-start: disable
  document-end: disable

  # Empty lines
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0

  # Trailing spaces
  trailing-spaces: enable

  # Truthy values
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: false

  # Quoted strings
  quoted-strings:
    quote-type: any
    required: only-when-needed

# Ignore paths
ignore: |
  node_modules/
  .git/
  dist/
  build/
  coverage/
  *.min.yml
  vendor/
