version: '3.8'

services:
  certbot:
    image: certbot/certbot
    restart: no
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --email admin@bsmarker.com -d bsmarker.utia.cas.cz --rsa-key-size 4096 --agree-tos --force-renewal

  nginx:
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
