# Generated by Django 5.0.4 on 2024-07-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wound_healing", "0002_remove_experiment_slug_remove_project_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="frame",
            options={"ordering": ["experiment", "number"]},
        ),
        migrations.AddField(
            model_name="polygon",
            name="operation",
            field=models.CharField(
                choices=[("+", "Add"), ("-", "Subtract")], default="+", max_length=1
            ),
        ),
    ]
