version = 5.1.0
archive_dir = /etc/letsencrypt/archive/bsmarker.utia.cas.cz
cert = /etc/letsencrypt/live/bsmarker.utia.cas.cz/cert.pem
privkey = /etc/letsencrypt/live/bsmarker.utia.cas.cz/privkey.pem
chain = /etc/letsencrypt/live/bsmarker.utia.cas.cz/chain.pem
fullchain = /etc/letsencrypt/live/bsmarker.utia.cas.cz/fullchain.pem
[renewalparams]
account = 8fca88016aa4ca52e027392e18b26d12
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
bsmarker.utia.cas.cz = /var/www/certbot
